#!/bin/bash

echo "Testing Israeli PM Marvel Series - Specific Episodes"
echo "==================================================="
echo ""
echo "Examples of usage:"
echo ""
echo "1. Generate specific episodes (e.g., 4, 6, 3, 8, 11, 2):"
echo "   ./create_israeli_pm_marvel_series.sh 4 6 3 8 11 2"
echo ""
echo "2. Generate all episodes:"
echo "   ./create_israeli_pm_marvel_series.sh"
echo ""
echo "3. Generate single episode:"
echo "   ./create_israeli_pm_marvel_series.sh 7"
echo ""
echo "Available episodes:"
echo "  1: Ben-Gurion"
echo "  2: Sharett" 
echo "  3: Eshkol"
echo "  4: Golda Meir"
echo "  5: Rabin I"
echo "  6: Begin"
echo "  7: Shamir"
echo "  8: Rabin II"
echo "  9: Peres"
echo " 10: Netanyahu I"
echo " 11: Barak"
echo " 12: Sharon"
echo " 13: Olmert"
echo " 14: Netanyahu II"
echo " 15: Bennett"
echo " 16: Lapid"
echo " 17: Netanyahu III"