#!/bin/bash

# Papaya Bar Ghibli Style Hebrew Ad - FIXED VERSION
# 40 seconds duration with proper Hebrew language handling

cd "$(dirname "$0")"

# Configuration (Duration aligned to multiple of 8 seconds)
DURATION=40  # 40 = 5 clips × 8 seconds each
STYLE="studio ghibli magical realism realistic characters"
THEME="whimsical"
PLATFORM="instagram"
LANGUAGE="he"

# Mission in English (Hebrew output will be generated by the system)
MISSION="Studio Ghibli magic! Welcome to the magical Papaya Bar in Rosh HaAyin, Israel. 
In an enchanted forest full of floating fruits and glowing sparkles, cute characters enjoy healthy and delicious drinks. 
During the day, families and young adults drink healthy shakes surrounded by magic and nature's blessings. 
In the evening, the same magical place serves special alcohol drinks with glowing effects. 
Soft colors, gentle animation, and charming Ghibli style. 
The Papaya Bar, Shabazi 47, Rosh HaAyin, Phone: 054-222-2617, Always Open.
Target: Health-conscious Israeli families and young adults."

echo "🌸 Generating Papaya Bar Ghibli-style Hebrew ad (FIXED VERSION)..."
echo "📍 Business: The Papaya Bar, שבזי 47, ראש העין"
echo "⏱️  Duration: ${DURATION}s | Platform: ${PLATFORM} | Language: עברית"

# Enhanced run with all latest fixes
python3 main.py generate \
    --mission "$MISSION" \
    --style cinematic \
    --theme "$THEME" \
    --duration $DURATION \
    --platform "$PLATFORM" \
    --languages "$LANGUAGE" \
    --character "פפיה קסומה - דמות חמודה בסגנון גיבלי עם כנפיים זוהרות ופירות מרחפים" \
    --tone inspiring \
    --visual-style "$STYLE" \
    --target-audience "israeli families health-conscious young adults" \
    --voice "he-IL-AvriNeural" \
    --business-name "The Papaya Bar" \
    --business-address "שבזי 47, ראש העין" \
    --business-phone "054-222-2617" \
    --business-website "thepapayabar.com" \
    --business-facebook "thepapayabar" \
    --business-instagram "@thepapayabar" \
    --show-business-info \
    --session-id "papaya_ghibli_hebrew_fixed_$(date +%Y%m%d_%H%M%S)" \
    --visual-continuity \
    --content-continuity \
    --no-cheap \
    --mode enhanced 2>&1 | tee ghibli_generation.log

EXIT_CODE=${PIPESTATUS[0]}

if [ $EXIT_CODE -eq 0 ]; then
    echo "✅ Papaya Bar Ghibli Hebrew ad generation completed successfully!"
    # Find and display the output video
    LATEST_SESSION=$(ls -td outputs/papaya_ghibli_hebrew_fixed_* 2>/dev/null | head -1)
    if [ -n "$LATEST_SESSION" ]; then
        echo "📁 Session: $LATEST_SESSION"
        find "$LATEST_SESSION/final_output" -name "*.mp4" -exec echo "🎬 Video: {}" \;
    fi
else
    echo "❌ Generation failed with exit code: $EXIT_CODE"
    echo "📋 Check ghibli_generation.log for details"
fi